---

  - name: Install build dependencies
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
      - maven
      - python-jenkins
      - python-lxml

  - name: Set NCSU Git credentials
    template: 
      src: credentials.xml.j2
      dest: /var/lib/jenkins/credentials.xml
      force: yes
      mode: 0644

  - name: Setup iTrust build job
    jenkins_job:
      name: iTrust
      state: present
      config: "{{ lookup('template', 'templates/iTrust.config.xml.j2') }}"

  - include: post_build.yml
  