---

  - name: Install build dependencies
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
      - maven
      - python-jenkins
      - python-lxml

  # - name: Set NCSU Git credentials
  #   template: 
  #     src: credentials.xml.j2
  #     dest: /var/lib/jenkins/credentials.xml
  #     force: yes
  #     mode: 0644

  - name: Create credentials
    raw: "curl -H $(curl -s 'http://{{ inventory_hostname }}:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)') -X POST 'http://{{ inventory_hostname }}:8080/credentials/store/system/domain/_/createCredentials' \
         --data-urlencode 'json={
          \"\": \"0\",
          \"credentials\": {
            \"scope\": \"GLOBAL\",
            \"id\": \"{{ cred_id }}\",
            \"username\": \"{{ cred_user }}\",
            \"password\": \"{{ cred_passwd }}\",
            \"description\": \"\",
            \"$class\": \"com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl\"
          }
        }'"

  - name: Setup iTrust build job
    jenkins_job:
      name: iTrust
      state: present
      config: "{{ lookup('template', 'templates/iTrust.config.xml.j2') }}"

  - include: post_build.yml
  