---

  - name: Install Nginx
    apt: 
      name: nginx
      state: present

  - name: Configure Nginx Default Server
    template: 
      src: nginx_default.j2
      dest: "{{ nginx_default }}/default"
      group: root
      owner: root

  - name: Restart Nginx
    service: 
      name: nginx
      state: restarted