---

- name: Add Mysql-5.6 repo
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu trusty universe
    state: present

- name: Install the MySQL packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: "{{ ubuntu_mysql_pkgs }}"
  register: res

- name: Start MySQL
  service: 
    name: mysql
    state: started

- name: Update MySQL root password for all root accounts 
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: res.changed == True

- name: Copy my.cnf template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root 
    group: root 
    mode: "{{ item.mode | default(644) }}"
  with_items:
    - { src: 'my.cnf.j2', dest: '/etc/mysql/my.cnf' }
  #  - { src: 'root.cnf.j2', dest: '/home/ubuntu/.my.cnf', mode: '600' }
  when: res.changed == True

- name: Restart MySQL
  service: 
    name: mysql
    state: restarted

- name: Clone git repo
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@github.ncsu.edu/dding3/iTrust-v23.git"
    dest: "{{ deploy_path }}/iTrust"

- name: Load data
  raw: cd "{{ deploy_path }}/iTrust/iTrust" && mvn -DskipTests=true package
