---

  - name: Add group "tomcat"
    group: 
      name: tomcat

  - name: Add user "tomcat"
    user: 
      name: tomcat
      group: tomcat 
      home: "{{ tomcat_path }}"
      createhome: no

  - name: Download Tomcat 9
    get_url: 
      url: "{{ tomcat_mirror }}"
      checksum: md5:29c36bbdd7c22a74603d3db04e946be0
      dest: "{{ deploy_path }}"
      mode: 0755

  - name: Extract Tomcat
    unarchive: 
      src: "{{ tomcat_mirror }}"
      dest: "{{ deploy_path }}"
      remote_src: yes
      mode: 0755

  - name: Symlink install directory
    file: 
      src: "{{ deploy_path }}/apache-tomcat-9.0.1" 
      path: "{{ tomcat_path }}"
      state: link

  - name: Change ownership of Tomcat installation
    file: 
      path: "{{ tomcat_path }}/"
      owner: tomcat
      group: tomcat
      state: directory
      recurse: yes

  # - name: Configure Tomcat server
  #   template: 
  #     src: server.xml.j2
  #     dest: /usr/share/tomcat/conf/server.xml
  #     group: tomcat
  #     owner: tomcat

  - name: Configure Tomcat users
    template: 
      src: tomcat-users.xml.j2
      dest: "{{ tomcat_path }}/conf/tomcat-users.xml"
      group: tomcat
      owner: tomcat

  - name: Install Tomcat init script
    copy: 
      src: tomcat-init.sh 
      dest: /etc/init.d/tomcat 
      mode: 0755

  - name: Start Tomcat
    systemd: 
      daemon_reload: yes
      name: tomcat
      state: started
      # enabled: yes

  - name: Restart Tomcat
    service: 
      name: tomcat 
      state: restarted

  - name: Wait for tomcat to start
    wait_for: 
      port: "{{ http_port }}"
