---

  - name: Clone Git Repo
    git: 
      repo: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@github.ncsu.edu/dding3/iTrust-v23.git"
      dest: "{{ workspace }}"
      version: "{{ workbranch }}"
      refspec: "+refs/heads/*:refs/remotes/origin/*"

  # - name: Install dependencies
  #   git: 
  #     repo: "https://github.com/musiKk/plyj.git"
  #     dest: "{{ basedir }}/plyj"

  # - name: Install dependencies
  #   raw: cd "{{ basedir }}/plyj" && python setup.py install

  - name: Copy fuzzer scripts
    copy: 
      src: "{{ item }}"
      dest: "{{ basedir }}/script/"
      mode: 0755
    with_items:
      - fuzzer.sh
      - detector.py
      - TestFuzzer.jar

  - name: Run fuzzer script
    raw: cd "{{ basedir }}/script/" && /bin/sh fuzzer.sh >> fuzzer.log
    args:
      creates: fuzzer.log