---

  - name: Install aptitude and update the package list
    apt: 
        name=aptitude
        update_cache=yes
      
  # This Java 8 installation method is for ubuntu 16.04, not guaranteed for other system
  - name: Install Java 8 
    apt: 
        name={{ item }} 
        state=present
    with_items:
        - default-jre
        - default-jdk
    tags: java8-install
    
  # This Java 8 installation method is for general ubuntu
  #- name: Add Java 8 repository
  #  apt_repository:
  #      repo: "ppa:webupd8team/java"
  #      state=present
  #      update_cache=yes
  #  tags: java8-install
    
  #- name: Install Java 8
  #  apt:
  #      name=oracle-java8-installer
  #      state=present
  #  tags: java8-install
        
  - name: Add Jenkins APT key
    apt_key:
        url="https://pkg.jenkins.io/debian/jenkins-ci.org.key"
        state=present
    tags: jenkins-install
        
  - name: Add Jenkins repository
    apt_repository:
        repo="deb http://pkg.jenkins.io/debian-stable binary/"
        state=present
    tags: jenkins-install
        
  - name: Install Jenkins
    apt: 
        name=jenkins
        update_cache=yes
    tags: jenkins-install
        
  #- name: Check Jenkins status
  #  service:
  #      name: jenkins.service
  #  register: jenkins_status
    
  - name: Start Jenkins
    service:
        name: jenkins.service
        state: started
        
  - name: Set Jenkins default file
    template: 
        src: jenkins.j2
        dest: /etc/default/jenkins
        force: yes
    tags: jenkins-config
        
  - name: Set Jenkins configure file to disable Jenkins security
    template: 
        src: config.xml.j2
        dest: /var/lib/jenkins/config.xml
        force: yes
    tags: jenkins-config
    
  - name: Restart Jenkins
    service:
        name: jenkins.service
        state: restarted
    tags: jenkins-config
    
  - name: Wait for Jenkins connection
    wait_for:
        host="127.0.0.1"
        port=8080 
        delay=10
        timeout=300

  - name: Install Jenkins plugins
    jenkins_plugin:
        name={{ item }}
        # owner: Jenkins
        # group: Jenkins
        # jenkins_home: /var/lib/jenkins
        # url: "http://localhost:8080"
    # with_dependencies: yes
    with_items:
        - javadoc
        - structs
        - junit
        - display-url-api
        - mailer
        - workflow-step-api
        - workflow-scm-step
        - credentials
        - script-security
        - matrix-project
        - scm-api
        - ssh-credentials
        - maven-plugin
        - git-client
        - git
        - jacoco
        - github-pullrequest
    tags: jenkins-plugin

  # Restart Jenkins again otherwise plugin won't take effect
  - name: Restart Jenkins
    service:
        name: jenkins.service
        state: restarted
    tags: jenkins-config

  - name: Wait for Jenkins connection
    wait_for:
        host="127.0.0.1"
        port=8080 
        delay=10
        timeout=300

