---

- name: Install necessary dependencies
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - unzip

- name: Create Nomad Config Directory
  file: path=/etc/nomad state=directory

- name: Unzip Nomad Binary
  unarchive:
    src: https://releases.hashicorp.com/nomad/0.7.0/nomad_0.7.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Unzip Consul Binary
  unarchive:
    src: https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Add Consul Service
  template:
    src: ConsolService.ini.j2
    dest: /etc/systemd/system/consul.service

- name: Make Sure Consul is Running
  systemd:
    state: restarted
    daemon_reload: yes
    name: consul

- name: Add Nomad Server Config
  template:
    src: nomad-server.hcl.j2
    dest: /etc/nomad/nomad-server.hcl

- name: Add Nomad Server.service
  template:
    src: nomad-server.service.j2
    dest: /etc/systemd/system/nomad-server.service

- name: Make Sure Nomad Server is Running
  systemd:
    state: restarted
    daemon_reload: yes
    name: nomad-server

- name: Set the Nomad Leader Server IP
  set_fact:
    nomad_leader_ip: '{{ ansible_default_ipv4.address }}'
  run_once: true

- name: Join servers 
  command: 'nomad server-join {{ nomad_leader_ip }}'

- name: Add Nomad Client Config
  template:
    src: nomad-client.hcl.j2
    dest: /etc/nomad/nomad-client.hcl

- name: Add Nomad Client.service
  template:
    src: nomad-client.service.j2
    dest: /etc/systemd/system/nomad-client.service

- name: Make Sure Nomad Client is Running
  systemd:
    state: restarted
    daemon_reload: yes
    name: nomad-client