---

  - name: Add Redis Repo into source list
    apt_repository:
      repo: 'ppa:chris-lea/redis-server'
      state: present
      update_cache: yes

  - name: Install Redis server
    apt:
      name: redis-server
      state: present

  - name: Create Feature Flag (Default off)
    command: redis-cli set mdFlag false


