---
- hosts: all
  become: yes
  become_method: sudo
  serial: 1

  tasks:
  - name: Stop Tomcat
    systemd: 
      name: tomcat
      state: stopped

  - name: Remove old war package
    file:
      state: absent
      path: /usr/share/tomcat/webapps/iTrust.war
  
  - name: Copy war package to remote directory
    copy: 
      src: /var/lib/jenkins/workspace/iTrust.war
      dest: /usr/share/tomcat/webapps/iTrust.war
      group: tomcat
      owner: tomcat

  - name: Start Tomcat
    systemd: 
      name: tomcat 
      state: started

  - name: Wait for tomcat to start
    wait_for: 
      port: 8080

  - name: Pause for 10 seconds
    pause:
      seconds: 10
  