---
- hosts: all
  become: yes
  become_method: sudo
  serial: 1

  tasks:
  - name: Stop Tomcat
    service: 
      name: tomcat
      state: stopped
      enable: yes

  # - name: Decommisioning iTrust application on this server
  #   pause:
  #     seconds: 10
  
  - name: Removed old war package
    file:
      state: absent
      path: /usr/share/tomcat/webapps/iTrust.war

  # - name: Remove old deploy dir
  #   raw: rm -rf /usr/share/tomcat/webapps/iTrust

  # - name: Create deploy directory
  #   file: 
  #     path: /usr/share/tomcat/webapps/iTrust
  #     state: directory
  #     owner: tomcat
  #     group: tomcat
  #     mode: 0755

  - name: Copy war package to remote directory
    copy: 
      src: /var/lib/jenkins/workspace/iTrust.war
      dest: /usr/share/tomcat/webapps/iTrust/iTrust.war

  # - name: Unzip war package
  #   shell: unzip -q iTrust.war
  #   args:
  #     chdir: /usr/share/tomcat/webapps/iTrust

  # - name: Change ownership of iTrust
  #   file: 
  #     path: /usr/share/tomcat/webapps/iTrust
  #     owner: tomcat
  #     group: tomcat
  #     state: directory
  #     recurse: yes

  - name: Restart Tomcat
    service: 
      name: tomcat 
      state: restarted
