---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:    
    - name: Provision of instance
      ec2:      
        aws_access_key: "AKIAJ7WKAPRDWPBR5PLQ"
        #aws_secret_key: {{ lookup('env', 'SK') }}
        aws_secret_key: "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"
        key_name: damon-personal
        instance_type: t2.micro
        image: ami-da05a4a0
        wait: yes
        wait_timeout: 600
        group_id: sg-f7dca788
        assign_public_ip: yes
        vpc_subnet_id: subnet-f5a5bad8
        region: us-east-1
        exact_count: 5
        count_tag:
          Name: itrust_pro
        instance_tags:
          Name: itrust_pro
      register: ec2
   
    # - name: Add new instance to host group
    #   add_host:
    #     hostname: "{{ item.public_ip }}"
    #     groupname: launched
    #   with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: print to file
      lineinfile:
        path: ./inventory
        state: present
        line: "{{ item.public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file=./keys/aws.pem"
      with_items: "{{ ec2.instances }}"
